services:
  postgres:
    container_name: postgres
    image: postgres
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    security_opt:
      - no-new-privileges:true

  app:
    container_name: app
    image: chatbot
    build: .
    platform: linux/amd64
    environment:
      AWS_DEFAULT_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      POSTGRES_HOST: postgres
    env_file: .env
    ports:
      - "8080:8080"
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /app/tmp

volumes:
  db:
    driver: local
